repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

      - id: ruff-format
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2  # Use the latest version
    hooks:
      - id: isort